[workspace]
resolver = "3"

[package]
name = "melior-autodiff"
version = "0.0.1"
edition = "2021"
description = "Automatic differentiation as a Melior pass"
license = "Apache-2.0"

[dependencies]
melior = { git = "https://github.com/agarret7/melior", branch = "main" }
mlir-sys = "230.0.1"

[build-dependencies]
bindgen = "0.73"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "gradient"
harness = false

[features]
default = ["melior-backend", "enzyme"]
melior-backend = []
enzyme = []
